// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ReportVacationStatus string

const (
	ReportVacationStatusConsideration ReportVacationStatus = "consideration"
	ReportVacationStatusRejected      ReportVacationStatus = "rejected"
	ReportVacationStatusApproved      ReportVacationStatus = "approved"
	ReportVacationStatusValue3        ReportVacationStatus = ""
)

func (e *ReportVacationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportVacationStatus(s)
	case string:
		*e = ReportVacationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportVacationStatus: %T", src)
	}
	return nil
}

type NullReportVacationStatus struct {
	ReportVacationStatus ReportVacationStatus `json:"reportVacationStatus"`
	Valid                bool                 `json:"valid"` // Valid is true if ReportVacationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportVacationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportVacationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportVacationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportVacationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportVacationStatus), nil
}

type ReportCalendar struct {
	ID             string         `json:"id"`
	Day            int32          `json:"day"`
	Month          int32          `json:"month"`
	Year           int32          `json:"year"`
	Description    sql.NullString `json:"description"`
	IsPaidVacation bool           `json:"isPaidVacation"`
	TypeID         string         `json:"typeId"`
}

type ReportSetting struct {
	ID               int32 `json:"id"`
	VacationDuration int32 `json:"vacationDuration"`
}

type ReportStandard struct {
	ID       string `json:"id"`
	Month    int32  `json:"month"`
	Year     int32  `json:"year"`
	Hours    int32  `json:"hours"`
	GenderID int32  `json:"genderId"`
}

type ReportType struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	SystemName string `json:"systemName"`
}

type ReportUser struct {
	ID     string  `json:"id"`
	UserID string  `json:"userId"`
	Day    int32   `json:"day"`
	Month  int32   `json:"month"`
	Year   int32   `json:"year"`
	Hours  float64 `json:"hours"`
	TypeID string  `json:"typeId"`
}

type ReportVacation struct {
	ID          string               `json:"id"`
	UserID      string               `json:"userId"`
	StartDate   time.Time            `json:"startDate"`
	EndDate     time.Time            `json:"endDate"`
	Year        int32                `json:"year"`
	Description sql.NullString       `json:"description"`
	Status      ReportVacationStatus `json:"status"`
	CreateAt    time.Time            `json:"createAt"`
}
