// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CheckDayExists(ctx context.Context, arg CheckDayExistsParams) (int64, error)
	CheckStandardExists(ctx context.Context, arg CheckStandardExistsParams) (int64, error)
	CheckUserReportExists(ctx context.Context, arg CheckUserReportExistsParams) (int64, error)
	CountDaysByType(ctx context.Context, arg CountDaysByTypeParams) (int64, error)
	CountDaysWork(ctx context.Context, arg CountDaysWorkParams) (int64, error)
	CreateDay(ctx context.Context, arg CreateDayParams) error
	CreateReportType(ctx context.Context, arg CreateReportTypeParams) error
	CreateStandardHours(ctx context.Context, arg CreateStandardHoursParams) error
	CreateUserReport(ctx context.Context, arg CreateUserReportParams) error
	CreateVacation(ctx context.Context, arg CreateVacationParams) error
	DeleteCalendarDay(ctx context.Context, id string) error
	DeleteReportType(ctx context.Context, id string) error
	DeleteStandardHours(ctx context.Context, id string) error
	DeleteUserReport(ctx context.Context, arg DeleteUserReportParams) error
	DeleteVacation(ctx context.Context, id string) error
	GetAllDays(ctx context.Context, year int32) ([]GetAllDaysRow, error)
	GetAllDaysByType(ctx context.Context, arg GetAllDaysByTypeParams) ([]GetAllDaysByTypeRow, error)
	GetAllReportTypes(ctx context.Context) ([]ReportType, error)
	GetDay(ctx context.Context, arg GetDayParams) (GetDayRow, error)
	// ============================================
	// REPORT_CALENDAR queries
	// ============================================
	GetDays(ctx context.Context, arg GetDaysParams) ([]GetDaysRow, error)
	GetDaysByType(ctx context.Context, arg GetDaysByTypeParams) ([]GetDaysByTypeRow, error)
	GetMonthTotalHours(ctx context.Context, arg GetMonthTotalHoursParams) (float64, error)
	// ============================================
	// REPORT_TYPE queries
	// ============================================
	GetReportTypeById(ctx context.Context, id string) (ReportType, error)
	GetReportTypeBySystemName(ctx context.Context, systemName string) (ReportType, error)
	// ============================================
	// REPORT_STANDART queries
	// ============================================
	GetStandardHours(ctx context.Context, arg GetStandardHoursParams) (ReportStandard, error)
	GetStandardHoursByMonth(ctx context.Context, arg GetStandardHoursByMonthParams) ([]ReportStandard, error)
	GetUserDayReport(ctx context.Context, id string) (GetUserDayReportRow, error)
	// ============================================
	// REPORT_USER queries
	// ============================================
	GetUserMonthReport(ctx context.Context, arg GetUserMonthReportParams) ([]GetUserMonthReportRow, error)
	// ============================================
	// REPORT_VACATION queries
	// ============================================
	GetUserVacations(ctx context.Context, userID string) ([]GetUserVacationsRow, error)
	GetUserVacationsByYear(ctx context.Context, arg GetUserVacationsByYearParams) ([]GetUserVacationsByYearRow, error)
	GetVacationApproved(ctx context.Context, userID string) ([]GetVacationApprovedRow, error)
	GetVacationById(ctx context.Context, id string) (GetVacationByIdRow, error)
	// ============================================
	// REPORT_SETTING queries
	// ============================================
	GetVacationDuration(ctx context.Context) (int32, error)
	GetVacationsByYear(ctx context.Context, year int32) ([]GetVacationsByYearRow, error)
	GetYearsVacation(ctx context.Context, userID string) ([]int32, error)
	UpdateDay(ctx context.Context, arg UpdateDayParams) error
	UpdateReportType(ctx context.Context, arg UpdateReportTypeParams) error
	UpdateStandardHours(ctx context.Context, arg UpdateStandardHoursParams) error
	UpdateUserReport(ctx context.Context, arg UpdateUserReportParams) error
	UpdateVacation(ctx context.Context, arg UpdateVacationParams) error
	UpdateVacationStatus(ctx context.Context, arg UpdateVacationStatusParams) error
}

var _ Querier = (*Queries)(nil)
