// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CheckCalendarDayExists(ctx context.Context, arg CheckCalendarDayExistsParams) (int64, error)
	CheckReportUserExists(ctx context.Context, arg CheckReportUserExistsParams) (int64, error)
	CheckStandard(ctx context.Context, arg CheckStandardParams) (int64, error)
	CreateCalendarDay(ctx context.Context, arg CreateCalendarDayParams) error
	CreateReportUser(ctx context.Context, arg CreateReportUserParams) error
	CreateStandard(ctx context.Context, arg CreateStandardParams) error
	CreateType(ctx context.Context, arg CreateTypeParams) error
	CreateVacation(ctx context.Context, arg CreateVacationParams) error
	DeleteCalendarDay(ctx context.Context, id string) error
	DeleteReportUser(ctx context.Context, arg DeleteReportUserParams) error
	DeleteStandard(ctx context.Context, id string) error
	DeleteType(ctx context.Context, id string) error
	DeleteVacation(ctx context.Context, id string) error
	GetAdminVacationsByYear(ctx context.Context, year int32) ([]GetAdminVacationsByYearRow, error)
	GetCalendarDay(ctx context.Context, arg GetCalendarDayParams) (GetCalendarDayRow, error)
	// ============================================
	// REPORT_CALENDAR queries
	// ============================================
	GetCalendarDays(ctx context.Context, arg GetCalendarDaysParams) ([]GetCalendarDaysRow, error)
	GetCalendarDaysAll(ctx context.Context, year int32) ([]GetCalendarDaysAllRow, error)
	GetCalendarDaysAllByType(ctx context.Context, arg GetCalendarDaysAllByTypeParams) ([]GetCalendarDaysAllByTypeRow, error)
	GetCalendarDaysByType(ctx context.Context, arg GetCalendarDaysByTypeParams) ([]GetCalendarDaysByTypeRow, error)
	GetReportUserById(ctx context.Context, id string) (GetReportUserByIdRow, error)
	GetReportUserCountByType(ctx context.Context, arg GetReportUserCountByTypeParams) (int64, error)
	GetReportUserCountWork(ctx context.Context, arg GetReportUserCountWorkParams) (int64, error)
	// ============================================
	// REPORT_USER queries
	// ============================================
	GetReportUserForMonth(ctx context.Context, arg GetReportUserForMonthParams) ([]GetReportUserForMonthRow, error)
	GetReportUserTotalHours(ctx context.Context, arg GetReportUserTotalHoursParams) (float64, error)
	// ============================================
	// REPORT_SETTING queries
	// ============================================
	GetSettingVacationDuration(ctx context.Context) (int32, error)
	// ============================================
	// REPORT_STANDART queries
	// ============================================
	GetStandard(ctx context.Context, arg GetStandardParams) (ReportStandard, error)
	GetStandardByMonth(ctx context.Context, arg GetStandardByMonthParams) ([]ReportStandard, error)
	GetStandardByYear(ctx context.Context, year int32) ([]ReportStandard, error)
	GetTypeAll(ctx context.Context) ([]ReportType, error)
	// ============================================
	// REPORT_TYPE queries
	// ============================================
	GetTypeById(ctx context.Context, id string) (ReportType, error)
	GetTypeBySystemName(ctx context.Context, systemName string) (ReportType, error)
	GetVacationApproved(ctx context.Context, userID string) ([]GetVacationApprovedRow, error)
	GetVacationById(ctx context.Context, id string) (GetVacationByIdRow, error)
	// ============================================
	// REPORT_VACATION queries
	// ============================================
	GetVacations(ctx context.Context, userID string) ([]GetVacationsRow, error)
	GetVacationsByYear(ctx context.Context, arg GetVacationsByYearParams) ([]GetVacationsByYearRow, error)
	GetYearsVacation(ctx context.Context, userID string) ([]int32, error)
	UpdateCalendarDay(ctx context.Context, arg UpdateCalendarDayParams) error
	UpdateReportUser(ctx context.Context, arg UpdateReportUserParams) error
	UpdateStandard(ctx context.Context, arg UpdateStandardParams) error
	UpdateType(ctx context.Context, arg UpdateTypeParams) error
	UpdateVacationStatus(ctx context.Context, arg UpdateVacationStatusParams) error
}

var _ Querier = (*Queries)(nil)
