// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_standard.sql

package repo

import (
	"context"
)

const checkStandard = `-- name: CheckStandard :one
SELECT COUNT(*) as exists_count
FROM report_standard
WHERE month = ? AND year = ? AND gender_id = ?
`

type CheckStandardParams struct {
	Month    int32 `json:"month"`
	Year     int32 `json:"year"`
	GenderID int32 `json:"genderId"`
}

func (q *Queries) CheckStandard(ctx context.Context, arg CheckStandardParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkStandard, arg.Month, arg.Year, arg.GenderID)
	var exists_count int64
	err := row.Scan(&exists_count)
	return exists_count, err
}

const createStandard = `-- name: CreateStandard :exec
INSERT INTO report_standard (id, month, year, hours, gender_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateStandardParams struct {
	ID       string `json:"id"`
	Month    int32  `json:"month"`
	Year     int32  `json:"year"`
	Hours    int32  `json:"hours"`
	GenderID int32  `json:"genderId"`
}

func (q *Queries) CreateStandard(ctx context.Context, arg CreateStandardParams) error {
	_, err := q.db.ExecContext(ctx, createStandard,
		arg.ID,
		arg.Month,
		arg.Year,
		arg.Hours,
		arg.GenderID,
	)
	return err
}

const deleteStandard = `-- name: DeleteStandard :exec
DELETE FROM report_standard
WHERE id = ?
`

func (q *Queries) DeleteStandard(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteStandard, id)
	return err
}

const getStandard = `-- name: GetStandard :one

SELECT id, month, year, hours, gender_id
FROM report_standard
WHERE month = ? AND year = ? AND gender_id = ?
`

type GetStandardParams struct {
	Month    int32 `json:"month"`
	Year     int32 `json:"year"`
	GenderID int32 `json:"genderId"`
}

// ============================================
// REPORT_STANDART queries
// ============================================
func (q *Queries) GetStandard(ctx context.Context, arg GetStandardParams) (ReportStandard, error) {
	row := q.db.QueryRowContext(ctx, getStandard, arg.Month, arg.Year, arg.GenderID)
	var i ReportStandard
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Year,
		&i.Hours,
		&i.GenderID,
	)
	return i, err
}

const getStandardByMonth = `-- name: GetStandardByMonth :many
SELECT id, month, year, hours, gender_id
FROM report_standard
WHERE month = ? AND year = ?
`

type GetStandardByMonthParams struct {
	Month int32 `json:"month"`
	Year  int32 `json:"year"`
}

func (q *Queries) GetStandardByMonth(ctx context.Context, arg GetStandardByMonthParams) ([]ReportStandard, error) {
	rows, err := q.db.QueryContext(ctx, getStandardByMonth, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportStandard
	for rows.Next() {
		var i ReportStandard
		if err := rows.Scan(
			&i.ID,
			&i.Month,
			&i.Year,
			&i.Hours,
			&i.GenderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStandardByYear = `-- name: GetStandardByYear :many
SELECT id, month, year, hours, gender_id
FROM report_standard
WHERE year = ?
ORDER BY month ASC
`

func (q *Queries) GetStandardByYear(ctx context.Context, year int32) ([]ReportStandard, error) {
	rows, err := q.db.QueryContext(ctx, getStandardByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportStandard
	for rows.Next() {
		var i ReportStandard
		if err := rows.Scan(
			&i.ID,
			&i.Month,
			&i.Year,
			&i.Hours,
			&i.GenderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStandard = `-- name: UpdateStandard :exec
UPDATE report_standard
SET hours = ?
WHERE id = ?
`

type UpdateStandardParams struct {
	Hours int32  `json:"hours"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateStandard(ctx context.Context, arg UpdateStandardParams) error {
	_, err := q.db.ExecContext(ctx, updateStandard, arg.Hours, arg.ID)
	return err
}
