// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_type.sql

package repo

import (
	"context"
)

const createType = `-- name: CreateType :exec
INSERT INTO report_type (id, name, system_name)
VALUES (?, ?, ?)
`

type CreateTypeParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	SystemName string `json:"systemName"`
}

func (q *Queries) CreateType(ctx context.Context, arg CreateTypeParams) error {
	_, err := q.db.ExecContext(ctx, createType, arg.ID, arg.Name, arg.SystemName)
	return err
}

const deleteType = `-- name: DeleteType :exec
DELETE FROM report_type
WHERE id = ?
`

func (q *Queries) DeleteType(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteType, id)
	return err
}

const getTypeAll = `-- name: GetTypeAll :many
SELECT id, name, system_name
FROM report_type
ORDER BY name ASC
`

func (q *Queries) GetTypeAll(ctx context.Context) ([]ReportType, error) {
	rows, err := q.db.QueryContext(ctx, getTypeAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportType
	for rows.Next() {
		var i ReportType
		if err := rows.Scan(&i.ID, &i.Name, &i.SystemName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTypeById = `-- name: GetTypeById :one

SELECT id, name, system_name
FROM report_type
WHERE id = ?
`

// ============================================
// REPORT_TYPE queries
// ============================================
func (q *Queries) GetTypeById(ctx context.Context, id string) (ReportType, error) {
	row := q.db.QueryRowContext(ctx, getTypeById, id)
	var i ReportType
	err := row.Scan(&i.ID, &i.Name, &i.SystemName)
	return i, err
}

const getTypeBySystemName = `-- name: GetTypeBySystemName :one
SELECT id, name, system_name
FROM report_type
WHERE system_name = ?
`

func (q *Queries) GetTypeBySystemName(ctx context.Context, systemName string) (ReportType, error) {
	row := q.db.QueryRowContext(ctx, getTypeBySystemName, systemName)
	var i ReportType
	err := row.Scan(&i.ID, &i.Name, &i.SystemName)
	return i, err
}

const updateType = `-- name: UpdateType :exec
UPDATE report_type
SET name = ?, system_name = ?
WHERE id = ?
`

type UpdateTypeParams struct {
	Name       string `json:"name"`
	SystemName string `json:"systemName"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateType(ctx context.Context, arg UpdateTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateType, arg.Name, arg.SystemName, arg.ID)
	return err
}
