// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_standard.sql

package repo

import (
	"context"
)

const checkStandardExists = `-- name: CheckStandardExists :one
SELECT COUNT(*) as exists_count
FROM report_standard
WHERE month = ? AND year = ? AND gender_id = ?
`

type CheckStandardExistsParams struct {
	Month    int32 `json:"month"`
	Year     int32 `json:"year"`
	GenderID int32 `json:"genderId"`
}

func (q *Queries) CheckStandardExists(ctx context.Context, arg CheckStandardExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkStandardExists, arg.Month, arg.Year, arg.GenderID)
	var exists_count int64
	err := row.Scan(&exists_count)
	return exists_count, err
}

const createStandardHours = `-- name: CreateStandardHours :exec
INSERT INTO report_standard (id, month, year, hours, gender_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateStandardHoursParams struct {
	ID       string `json:"id"`
	Month    int32  `json:"month"`
	Year     int32  `json:"year"`
	Hours    int32  `json:"hours"`
	GenderID int32  `json:"genderId"`
}

func (q *Queries) CreateStandardHours(ctx context.Context, arg CreateStandardHoursParams) error {
	_, err := q.db.ExecContext(ctx, createStandardHours,
		arg.ID,
		arg.Month,
		arg.Year,
		arg.Hours,
		arg.GenderID,
	)
	return err
}

const deleteStandardHours = `-- name: DeleteStandardHours :exec
DELETE FROM report_standard
WHERE id = ?
`

func (q *Queries) DeleteStandardHours(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteStandardHours, id)
	return err
}

const getStandardHours = `-- name: GetStandardHours :one

SELECT id, month, year, hours, gender_id
FROM report_standard
WHERE month = ? AND year = ? AND gender_id = ?
`

type GetStandardHoursParams struct {
	Month    int32 `json:"month"`
	Year     int32 `json:"year"`
	GenderID int32 `json:"genderId"`
}

// ============================================
// REPORT_STANDART queries
// ============================================
func (q *Queries) GetStandardHours(ctx context.Context, arg GetStandardHoursParams) (ReportStandard, error) {
	row := q.db.QueryRowContext(ctx, getStandardHours, arg.Month, arg.Year, arg.GenderID)
	var i ReportStandard
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Year,
		&i.Hours,
		&i.GenderID,
	)
	return i, err
}

const getStandardHoursByMonth = `-- name: GetStandardHoursByMonth :many
SELECT id, month, year, hours, gender_id
FROM report_standard
WHERE month = ? AND year = ?
`

type GetStandardHoursByMonthParams struct {
	Month int32 `json:"month"`
	Year  int32 `json:"year"`
}

func (q *Queries) GetStandardHoursByMonth(ctx context.Context, arg GetStandardHoursByMonthParams) ([]ReportStandard, error) {
	rows, err := q.db.QueryContext(ctx, getStandardHoursByMonth, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportStandard
	for rows.Next() {
		var i ReportStandard
		if err := rows.Scan(
			&i.ID,
			&i.Month,
			&i.Year,
			&i.Hours,
			&i.GenderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStandardHours = `-- name: UpdateStandardHours :exec
UPDATE report_standard
SET hours = ?
WHERE id = ?
`

type UpdateStandardHoursParams struct {
	Hours int32  `json:"hours"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateStandardHours(ctx context.Context, arg UpdateStandardHoursParams) error {
	_, err := q.db.ExecContext(ctx, updateStandardHours, arg.Hours, arg.ID)
	return err
}
