// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_calendar.sql

package repo

import (
	"context"
	"database/sql"
)

const checkDayExists = `-- name: CheckDayExists :one
SELECT COUNT(*) as exists_count
FROM report_calendar
WHERE day = ? AND month = ? AND year = ?
`

type CheckDayExistsParams struct {
	Day   int32 `json:"day"`
	Month int32 `json:"month"`
	Year  int32 `json:"year"`
}

func (q *Queries) CheckDayExists(ctx context.Context, arg CheckDayExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkDayExists, arg.Day, arg.Month, arg.Year)
	var exists_count int64
	err := row.Scan(&exists_count)
	return exists_count, err
}

const createDay = `-- name: CreateDay :exec
INSERT INTO report_calendar (id, day, month, year, description, is_paid_vacation, type_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateDayParams struct {
	ID             string         `json:"id"`
	Day            int32          `json:"day"`
	Month          int32          `json:"month"`
	Year           int32          `json:"year"`
	Description    sql.NullString `json:"description"`
	IsPaidVacation bool           `json:"isPaidVacation"`
	TypeID         string         `json:"typeId"`
}

func (q *Queries) CreateDay(ctx context.Context, arg CreateDayParams) error {
	_, err := q.db.ExecContext(ctx, createDay,
		arg.ID,
		arg.Day,
		arg.Month,
		arg.Year,
		arg.Description,
		arg.IsPaidVacation,
		arg.TypeID,
	)
	return err
}

const deleteCalendarDay = `-- name: DeleteCalendarDay :exec
DELETE FROM report_calendar
WHERE id = ?
`

func (q *Queries) DeleteCalendarDay(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCalendarDay, id)
	return err
}

const getAllDays = `-- name: GetAllDays :many
SELECT
    rc.id,
    rc.day,
    rc.month,
    rc.year,
    COALESCE(rc.description, '') as description,  -- Возвращаем пустую строку вместо NULL
    rc.is_paid_vacation,
    rc.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_calendar rc
INNER JOIN report_type rt ON rc.type_id = rt.id
WHERE rc.year = ?
ORDER BY rc.day ASC
`

type GetAllDaysRow struct {
	ID             string `json:"id"`
	Day            int32  `json:"day"`
	Month          int32  `json:"month"`
	Year           int32  `json:"year"`
	Description    string `json:"description"`
	IsPaidVacation bool   `json:"isPaidVacation"`
	TypeID         string `json:"typeId"`
	TypeName       string `json:"typeName"`
	TypeSystemName string `json:"typeSystemName"`
}

func (q *Queries) GetAllDays(ctx context.Context, year int32) ([]GetAllDaysRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllDays, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDaysRow
	for rows.Next() {
		var i GetAllDaysRow
		if err := rows.Scan(
			&i.ID,
			&i.Day,
			&i.Month,
			&i.Year,
			&i.Description,
			&i.IsPaidVacation,
			&i.TypeID,
			&i.TypeName,
			&i.TypeSystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDaysByType = `-- name: GetAllDaysByType :many
SELECT
    rc.id,
    rc.day,
    rc.month,
    rc.year,
    COALESCE(rc.description, '') as description,  -- Возвращаем пустую строку вместо NULL
    rc.is_paid_vacation,
    rc.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_calendar rc
INNER JOIN report_type rt ON rc.type_id = rt.id
WHERE rc.year = ? AND rt.system_name = ?
ORDER BY rc.day ASC
`

type GetAllDaysByTypeParams struct {
	Year       int32  `json:"year"`
	SystemName string `json:"systemName"`
}

type GetAllDaysByTypeRow struct {
	ID             string `json:"id"`
	Day            int32  `json:"day"`
	Month          int32  `json:"month"`
	Year           int32  `json:"year"`
	Description    string `json:"description"`
	IsPaidVacation bool   `json:"isPaidVacation"`
	TypeID         string `json:"typeId"`
	TypeName       string `json:"typeName"`
	TypeSystemName string `json:"typeSystemName"`
}

func (q *Queries) GetAllDaysByType(ctx context.Context, arg GetAllDaysByTypeParams) ([]GetAllDaysByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllDaysByType, arg.Year, arg.SystemName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDaysByTypeRow
	for rows.Next() {
		var i GetAllDaysByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Day,
			&i.Month,
			&i.Year,
			&i.Description,
			&i.IsPaidVacation,
			&i.TypeID,
			&i.TypeName,
			&i.TypeSystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDay = `-- name: GetDay :one
SELECT
    rc.id,
    rc.day,
    rc.month,
    rc.year,
    rc.description,
    rc.is_paid_vacation,
    rc.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_calendar rc
INNER JOIN report_type rt ON rc.type_id = rt.id
WHERE rc.day = ? AND rc.month = ? AND rc.year = ?
`

type GetDayParams struct {
	Day   int32 `json:"day"`
	Month int32 `json:"month"`
	Year  int32 `json:"year"`
}

type GetDayRow struct {
	ID             string         `json:"id"`
	Day            int32          `json:"day"`
	Month          int32          `json:"month"`
	Year           int32          `json:"year"`
	Description    sql.NullString `json:"description"`
	IsPaidVacation bool           `json:"isPaidVacation"`
	TypeID         string         `json:"typeId"`
	TypeName       string         `json:"typeName"`
	TypeSystemName string         `json:"typeSystemName"`
}

func (q *Queries) GetDay(ctx context.Context, arg GetDayParams) (GetDayRow, error) {
	row := q.db.QueryRowContext(ctx, getDay, arg.Day, arg.Month, arg.Year)
	var i GetDayRow
	err := row.Scan(
		&i.ID,
		&i.Day,
		&i.Month,
		&i.Year,
		&i.Description,
		&i.IsPaidVacation,
		&i.TypeID,
		&i.TypeName,
		&i.TypeSystemName,
	)
	return i, err
}

const getDays = `-- name: GetDays :many

SELECT
    rc.id,
    rc.day,
    rc.month,
    rc.year,
    COALESCE(rc.description, '') as description,  -- Возвращаем пустую строку вместо NULL
    rc.is_paid_vacation,
    rc.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_calendar rc
INNER JOIN report_type rt ON rc.type_id = rt.id
WHERE rc.month = ? AND rc.year = ?
ORDER BY rc.day ASC
`

type GetDaysParams struct {
	Month int32 `json:"month"`
	Year  int32 `json:"year"`
}

type GetDaysRow struct {
	ID             string `json:"id"`
	Day            int32  `json:"day"`
	Month          int32  `json:"month"`
	Year           int32  `json:"year"`
	Description    string `json:"description"`
	IsPaidVacation bool   `json:"isPaidVacation"`
	TypeID         string `json:"typeId"`
	TypeName       string `json:"typeName"`
	TypeSystemName string `json:"typeSystemName"`
}

// ============================================
// REPORT_CALENDAR queries
// ============================================
func (q *Queries) GetDays(ctx context.Context, arg GetDaysParams) ([]GetDaysRow, error) {
	rows, err := q.db.QueryContext(ctx, getDays, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDaysRow
	for rows.Next() {
		var i GetDaysRow
		if err := rows.Scan(
			&i.ID,
			&i.Day,
			&i.Month,
			&i.Year,
			&i.Description,
			&i.IsPaidVacation,
			&i.TypeID,
			&i.TypeName,
			&i.TypeSystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDaysByType = `-- name: GetDaysByType :many
SELECT
    rc.id,
    rc.day,
    rc.month,
    rc.year,
    COALESCE(rc.description, '') as description,  -- Возвращаем пустую строку вместо NULL
    rc.is_paid_vacation,
    rc.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_calendar rc
INNER JOIN report_type rt ON rc.type_id = rt.id
WHERE rc.month = ? AND rc.year = ? AND rt.system_name = ?
ORDER BY rc.day ASC
`

type GetDaysByTypeParams struct {
	Month      int32  `json:"month"`
	Year       int32  `json:"year"`
	SystemName string `json:"systemName"`
}

type GetDaysByTypeRow struct {
	ID             string `json:"id"`
	Day            int32  `json:"day"`
	Month          int32  `json:"month"`
	Year           int32  `json:"year"`
	Description    string `json:"description"`
	IsPaidVacation bool   `json:"isPaidVacation"`
	TypeID         string `json:"typeId"`
	TypeName       string `json:"typeName"`
	TypeSystemName string `json:"typeSystemName"`
}

func (q *Queries) GetDaysByType(ctx context.Context, arg GetDaysByTypeParams) ([]GetDaysByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getDaysByType, arg.Month, arg.Year, arg.SystemName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDaysByTypeRow
	for rows.Next() {
		var i GetDaysByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Day,
			&i.Month,
			&i.Year,
			&i.Description,
			&i.IsPaidVacation,
			&i.TypeID,
			&i.TypeName,
			&i.TypeSystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDay = `-- name: UpdateDay :exec
UPDATE report_calendar
SET description = ?, type_id = ?
WHERE id = ?
`

type UpdateDayParams struct {
	Description sql.NullString `json:"description"`
	TypeID      string         `json:"typeId"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateDay(ctx context.Context, arg UpdateDayParams) error {
	_, err := q.db.ExecContext(ctx, updateDay, arg.Description, arg.TypeID, arg.ID)
	return err
}
