// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_type.sql

package repo

import (
	"context"
)

const createReportType = `-- name: CreateReportType :exec
INSERT INTO report_type (id, name, system_name)
VALUES (?, ?, ?)
`

type CreateReportTypeParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	SystemName string `json:"systemName"`
}

func (q *Queries) CreateReportType(ctx context.Context, arg CreateReportTypeParams) error {
	_, err := q.db.ExecContext(ctx, createReportType, arg.ID, arg.Name, arg.SystemName)
	return err
}

const deleteReportType = `-- name: DeleteReportType :exec
DELETE FROM report_type
WHERE id = ?
`

func (q *Queries) DeleteReportType(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteReportType, id)
	return err
}

const getAllReportTypes = `-- name: GetAllReportTypes :many
SELECT id, name, system_name
FROM report_type
ORDER BY name ASC
`

func (q *Queries) GetAllReportTypes(ctx context.Context) ([]ReportType, error) {
	rows, err := q.db.QueryContext(ctx, getAllReportTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportType
	for rows.Next() {
		var i ReportType
		if err := rows.Scan(&i.ID, &i.Name, &i.SystemName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportTypeById = `-- name: GetReportTypeById :one

SELECT id, name, system_name
FROM report_type
WHERE id = ?
`

// ============================================
// REPORT_TYPE queries
// ============================================
func (q *Queries) GetReportTypeById(ctx context.Context, id string) (ReportType, error) {
	row := q.db.QueryRowContext(ctx, getReportTypeById, id)
	var i ReportType
	err := row.Scan(&i.ID, &i.Name, &i.SystemName)
	return i, err
}

const getReportTypeBySystemName = `-- name: GetReportTypeBySystemName :one
SELECT id, name, system_name
FROM report_type
WHERE system_name = ?
`

func (q *Queries) GetReportTypeBySystemName(ctx context.Context, systemName string) (ReportType, error) {
	row := q.db.QueryRowContext(ctx, getReportTypeBySystemName, systemName)
	var i ReportType
	err := row.Scan(&i.ID, &i.Name, &i.SystemName)
	return i, err
}

const updateReportType = `-- name: UpdateReportType :exec
UPDATE report_type
SET name = ?, system_name = ?
WHERE id = ?
`

type UpdateReportTypeParams struct {
	Name       string `json:"name"`
	SystemName string `json:"systemName"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateReportType(ctx context.Context, arg UpdateReportTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateReportType, arg.Name, arg.SystemName, arg.ID)
	return err
}
