// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_vacation.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const createVacation = `-- name: CreateVacation :exec
INSERT INTO report_vacation (id, user_id, start_date, end_date, year,  description, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateVacationParams struct {
	ID          string               `json:"id"`
	UserID      string               `json:"userId"`
	StartDate   time.Time            `json:"startDate"`
	EndDate     time.Time            `json:"endDate"`
	Year        int32                `json:"year"`
	Description sql.NullString       `json:"description"`
	Status      ReportVacationStatus `json:"status"`
}

func (q *Queries) CreateVacation(ctx context.Context, arg CreateVacationParams) error {
	_, err := q.db.ExecContext(ctx, createVacation,
		arg.ID,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.Year,
		arg.Description,
		arg.Status,
	)
	return err
}

const deleteVacation = `-- name: DeleteVacation :exec
DELETE FROM report_vacation
WHERE id = ?
`

func (q *Queries) DeleteVacation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteVacation, id)
	return err
}

const getUserVacations = `-- name: GetUserVacations :many

SELECT id, user_id, start_date, end_date, year, COALESCE(description, '') as description, status, create_at
FROM report_vacation
WHERE user_id = ?
ORDER BY create_at DESC
`

type GetUserVacationsRow struct {
	ID          string               `json:"id"`
	UserID      string               `json:"userId"`
	StartDate   time.Time            `json:"startDate"`
	EndDate     time.Time            `json:"endDate"`
	Year        int32                `json:"year"`
	Description string               `json:"description"`
	Status      ReportVacationStatus `json:"status"`
	CreateAt    time.Time            `json:"createAt"`
}

// ============================================
// REPORT_VACATION queries
// ============================================
func (q *Queries) GetUserVacations(ctx context.Context, userID string) ([]GetUserVacationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserVacations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserVacationsRow
	for rows.Next() {
		var i GetUserVacationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.Year,
			&i.Description,
			&i.Status,
			&i.CreateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVacationsByYear = `-- name: GetUserVacationsByYear :many
SELECT id, user_id, start_date, end_date, year, COALESCE(description, '') as description, status, create_at
FROM report_vacation
WHERE user_id = ? AND year = ?
ORDER BY create_at DESC
`

type GetUserVacationsByYearParams struct {
	UserID string `json:"userId"`
	Year   int32  `json:"year"`
}

type GetUserVacationsByYearRow struct {
	ID          string               `json:"id"`
	UserID      string               `json:"userId"`
	StartDate   time.Time            `json:"startDate"`
	EndDate     time.Time            `json:"endDate"`
	Year        int32                `json:"year"`
	Description string               `json:"description"`
	Status      ReportVacationStatus `json:"status"`
	CreateAt    time.Time            `json:"createAt"`
}

func (q *Queries) GetUserVacationsByYear(ctx context.Context, arg GetUserVacationsByYearParams) ([]GetUserVacationsByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserVacationsByYear, arg.UserID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserVacationsByYearRow
	for rows.Next() {
		var i GetUserVacationsByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.Year,
			&i.Description,
			&i.Status,
			&i.CreateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVacationApproved = `-- name: GetVacationApproved :many
SELECT id, user_id, start_date, end_date, year, COALESCE(description, '') as description, status, create_at
FROM report_vacation
WHERE user_id = ? AND status = "approved"
`

type GetVacationApprovedRow struct {
	ID          string               `json:"id"`
	UserID      string               `json:"userId"`
	StartDate   time.Time            `json:"startDate"`
	EndDate     time.Time            `json:"endDate"`
	Year        int32                `json:"year"`
	Description string               `json:"description"`
	Status      ReportVacationStatus `json:"status"`
	CreateAt    time.Time            `json:"createAt"`
}

func (q *Queries) GetVacationApproved(ctx context.Context, userID string) ([]GetVacationApprovedRow, error) {
	rows, err := q.db.QueryContext(ctx, getVacationApproved, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVacationApprovedRow
	for rows.Next() {
		var i GetVacationApprovedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.Year,
			&i.Description,
			&i.Status,
			&i.CreateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVacationById = `-- name: GetVacationById :one
SELECT id, user_id, start_date, end_date, year, COALESCE(description, '') as description, status, create_at
FROM report_vacation
WHERE id = ?
`

type GetVacationByIdRow struct {
	ID          string               `json:"id"`
	UserID      string               `json:"userId"`
	StartDate   time.Time            `json:"startDate"`
	EndDate     time.Time            `json:"endDate"`
	Year        int32                `json:"year"`
	Description string               `json:"description"`
	Status      ReportVacationStatus `json:"status"`
	CreateAt    time.Time            `json:"createAt"`
}

func (q *Queries) GetVacationById(ctx context.Context, id string) (GetVacationByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getVacationById, id)
	var i GetVacationByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Year,
		&i.Description,
		&i.Status,
		&i.CreateAt,
	)
	return i, err
}

const getVacationsByYear = `-- name: GetVacationsByYear :many
SELECT id, user_id, start_date, end_date, year, COALESCE(description, '') as description, status, create_at
FROM report_vacation
WHERE year = ?
ORDER BY create_at DESC
`

type GetVacationsByYearRow struct {
	ID          string               `json:"id"`
	UserID      string               `json:"userId"`
	StartDate   time.Time            `json:"startDate"`
	EndDate     time.Time            `json:"endDate"`
	Year        int32                `json:"year"`
	Description string               `json:"description"`
	Status      ReportVacationStatus `json:"status"`
	CreateAt    time.Time            `json:"createAt"`
}

func (q *Queries) GetVacationsByYear(ctx context.Context, year int32) ([]GetVacationsByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getVacationsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVacationsByYearRow
	for rows.Next() {
		var i GetVacationsByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.Year,
			&i.Description,
			&i.Status,
			&i.CreateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYearsVacation = `-- name: GetYearsVacation :many
SELECT DISTINCT year
FROM report_vacation
WHERE user_id = ?
ORDER BY year DESC
`

func (q *Queries) GetYearsVacation(ctx context.Context, userID string) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getYearsVacation, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var year int32
		if err := rows.Scan(&year); err != nil {
			return nil, err
		}
		items = append(items, year)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVacation = `-- name: UpdateVacation :exec
UPDATE report_vacation
SET start_date = ?, end_date = ?, year = ?, status = ?,  description = ?
WHERE id = ?
`

type UpdateVacationParams struct {
	StartDate   time.Time            `json:"startDate"`
	EndDate     time.Time            `json:"endDate"`
	Year        int32                `json:"year"`
	Status      ReportVacationStatus `json:"status"`
	Description sql.NullString       `json:"description"`
	ID          string               `json:"id"`
}

func (q *Queries) UpdateVacation(ctx context.Context, arg UpdateVacationParams) error {
	_, err := q.db.ExecContext(ctx, updateVacation,
		arg.StartDate,
		arg.EndDate,
		arg.Year,
		arg.Status,
		arg.Description,
		arg.ID,
	)
	return err
}

const updateVacationStatus = `-- name: UpdateVacationStatus :exec
UPDATE report_vacation
SET status = ?
WHERE id = ?
`

type UpdateVacationStatusParams struct {
	Status ReportVacationStatus `json:"status"`
	ID     string               `json:"id"`
}

func (q *Queries) UpdateVacationStatus(ctx context.Context, arg UpdateVacationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVacationStatus, arg.Status, arg.ID)
	return err
}
