// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_user.sql

package repo

import (
	"context"
)

const checkUserReportExists = `-- name: CheckUserReportExists :one
SELECT COUNT(*) as exists_count
FROM report_user
WHERE user_id = ? AND day = ? AND month = ? AND year = ?
`

type CheckUserReportExistsParams struct {
	UserID string `json:"userId"`
	Day    int32  `json:"day"`
	Month  int32  `json:"month"`
	Year   int32  `json:"year"`
}

func (q *Queries) CheckUserReportExists(ctx context.Context, arg CheckUserReportExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkUserReportExists,
		arg.UserID,
		arg.Day,
		arg.Month,
		arg.Year,
	)
	var exists_count int64
	err := row.Scan(&exists_count)
	return exists_count, err
}

const countDaysByType = `-- name: CountDaysByType :one
SELECT COUNT(DISTINCT day) as days_count
FROM report_user
WHERE user_id = ? AND month = ? AND year = ? AND type_id = ?
`

type CountDaysByTypeParams struct {
	UserID string `json:"userId"`
	Month  int32  `json:"month"`
	Year   int32  `json:"year"`
	TypeID string `json:"typeId"`
}

func (q *Queries) CountDaysByType(ctx context.Context, arg CountDaysByTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDaysByType,
		arg.UserID,
		arg.Month,
		arg.Year,
		arg.TypeID,
	)
	var days_count int64
	err := row.Scan(&days_count)
	return days_count, err
}

const countDaysWork = `-- name: CountDaysWork :one
SELECT COUNT(DISTINCT day) as days_count
FROM report_user ru
INNER JOIN report_type rt ON ru.type_id = rt.id
WHERE ru.user_id = ? AND ru.month = ? AND ru.year = ? AND (rt.system_name = 'work' OR rt.system_name = 'weekend')
`

type CountDaysWorkParams struct {
	UserID string `json:"userId"`
	Month  int32  `json:"month"`
	Year   int32  `json:"year"`
}

func (q *Queries) CountDaysWork(ctx context.Context, arg CountDaysWorkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDaysWork, arg.UserID, arg.Month, arg.Year)
	var days_count int64
	err := row.Scan(&days_count)
	return days_count, err
}

const createUserReport = `-- name: CreateUserReport :exec
INSERT INTO report_user (id, user_id, day, month, year, hours, type_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateUserReportParams struct {
	ID     string  `json:"id"`
	UserID string  `json:"userId"`
	Day    int32   `json:"day"`
	Month  int32   `json:"month"`
	Year   int32   `json:"year"`
	Hours  float64 `json:"hours"`
	TypeID string  `json:"typeId"`
}

func (q *Queries) CreateUserReport(ctx context.Context, arg CreateUserReportParams) error {
	_, err := q.db.ExecContext(ctx, createUserReport,
		arg.ID,
		arg.UserID,
		arg.Day,
		arg.Month,
		arg.Year,
		arg.Hours,
		arg.TypeID,
	)
	return err
}

const deleteUserReport = `-- name: DeleteUserReport :exec
DELETE FROM report_user
WHERE user_id = ? AND day = ? AND month = ? AND year = ?
`

type DeleteUserReportParams struct {
	UserID string `json:"userId"`
	Day    int32  `json:"day"`
	Month  int32  `json:"month"`
	Year   int32  `json:"year"`
}

func (q *Queries) DeleteUserReport(ctx context.Context, arg DeleteUserReportParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserReport,
		arg.UserID,
		arg.Day,
		arg.Month,
		arg.Year,
	)
	return err
}

const getMonthTotalHours = `-- name: GetMonthTotalHours :one
SELECT CAST(COALESCE(SUM(hours), 0.0) AS FLOAT) AS total_hours
FROM report_user
WHERE user_id = ? AND month = ? AND year = ?
`

type GetMonthTotalHoursParams struct {
	UserID string `json:"userId"`
	Month  int32  `json:"month"`
	Year   int32  `json:"year"`
}

func (q *Queries) GetMonthTotalHours(ctx context.Context, arg GetMonthTotalHoursParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getMonthTotalHours, arg.UserID, arg.Month, arg.Year)
	var total_hours float64
	err := row.Scan(&total_hours)
	return total_hours, err
}

const getUserDayReport = `-- name: GetUserDayReport :one
SELECT
    ru.id,
    ru.user_id,
    ru.day,
    ru.month,
    ru.year,
    ru.hours,
    ru.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_user ru
INNER JOIN report_type rt ON ru.type_id = rt.id
WHERE ru.id = ?
`

type GetUserDayReportRow struct {
	ID             string  `json:"id"`
	UserID         string  `json:"userId"`
	Day            int32   `json:"day"`
	Month          int32   `json:"month"`
	Year           int32   `json:"year"`
	Hours          float64 `json:"hours"`
	TypeID         string  `json:"typeId"`
	TypeName       string  `json:"typeName"`
	TypeSystemName string  `json:"typeSystemName"`
}

func (q *Queries) GetUserDayReport(ctx context.Context, id string) (GetUserDayReportRow, error) {
	row := q.db.QueryRowContext(ctx, getUserDayReport, id)
	var i GetUserDayReportRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.Month,
		&i.Year,
		&i.Hours,
		&i.TypeID,
		&i.TypeName,
		&i.TypeSystemName,
	)
	return i, err
}

const getUserMonthReport = `-- name: GetUserMonthReport :many

SELECT
    ru.id,
    ru.user_id,
    ru.day,
    ru.month,
    ru.year,
    ru.hours,
    ru.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_user ru
INNER JOIN report_type rt ON ru.type_id = rt.id
WHERE ru.user_id = ? AND ru.month = ? AND ru.year = ?
ORDER BY ru.day ASC
`

type GetUserMonthReportParams struct {
	UserID string `json:"userId"`
	Month  int32  `json:"month"`
	Year   int32  `json:"year"`
}

type GetUserMonthReportRow struct {
	ID             string  `json:"id"`
	UserID         string  `json:"userId"`
	Day            int32   `json:"day"`
	Month          int32   `json:"month"`
	Year           int32   `json:"year"`
	Hours          float64 `json:"hours"`
	TypeID         string  `json:"typeId"`
	TypeName       string  `json:"typeName"`
	TypeSystemName string  `json:"typeSystemName"`
}

// ============================================
// REPORT_USER queries
// ============================================
func (q *Queries) GetUserMonthReport(ctx context.Context, arg GetUserMonthReportParams) ([]GetUserMonthReportRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserMonthReport, arg.UserID, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserMonthReportRow
	for rows.Next() {
		var i GetUserMonthReportRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Day,
			&i.Month,
			&i.Year,
			&i.Hours,
			&i.TypeID,
			&i.TypeName,
			&i.TypeSystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserReport = `-- name: UpdateUserReport :exec
UPDATE report_user
SET hours = ?, type_id = ?
WHERE id = ?
`

type UpdateUserReportParams struct {
	Hours  float64 `json:"hours"`
	TypeID string  `json:"typeId"`
	ID     string  `json:"id"`
}

func (q *Queries) UpdateUserReport(ctx context.Context, arg UpdateUserReportParams) error {
	_, err := q.db.ExecContext(ctx, updateUserReport, arg.Hours, arg.TypeID, arg.ID)
	return err
}
