// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_calendar.sql

package repo

import (
	"context"
	"database/sql"
)

const checkCalendarDayExists = `-- name: CheckCalendarDayExists :one
SELECT COUNT(*) as exists_count
FROM report_calendar
WHERE day = ? AND month = ? AND year = ?
`

type CheckCalendarDayExistsParams struct {
	Day   int32 `json:"day"`
	Month int32 `json:"month"`
	Year  int32 `json:"year"`
}

func (q *Queries) CheckCalendarDayExists(ctx context.Context, arg CheckCalendarDayExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCalendarDayExists, arg.Day, arg.Month, arg.Year)
	var exists_count int64
	err := row.Scan(&exists_count)
	return exists_count, err
}

const createCalendarDay = `-- name: CreateCalendarDay :exec
INSERT INTO report_calendar (id, day, month, year, description, is_paid_vacation, type_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateCalendarDayParams struct {
	ID             string         `json:"id"`
	Day            int32          `json:"day"`
	Month          int32          `json:"month"`
	Year           int32          `json:"year"`
	Description    sql.NullString `json:"description"`
	IsPaidVacation bool           `json:"isPaidVacation"`
	TypeID         string         `json:"typeId"`
}

func (q *Queries) CreateCalendarDay(ctx context.Context, arg CreateCalendarDayParams) error {
	_, err := q.db.ExecContext(ctx, createCalendarDay,
		arg.ID,
		arg.Day,
		arg.Month,
		arg.Year,
		arg.Description,
		arg.IsPaidVacation,
		arg.TypeID,
	)
	return err
}

const deleteCalendarDay = `-- name: DeleteCalendarDay :exec
DELETE FROM report_calendar
WHERE id = ?
`

func (q *Queries) DeleteCalendarDay(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCalendarDay, id)
	return err
}

const getCalendarDay = `-- name: GetCalendarDay :one
SELECT
    rc.id,
    rc.day,
    rc.month,
    rc.year,
    rc.description,
    rc.is_paid_vacation,
    rc.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_calendar rc
INNER JOIN report_type rt ON rc.type_id = rt.id
WHERE rc.day = ? AND rc.month = ? AND rc.year = ?
`

type GetCalendarDayParams struct {
	Day   int32 `json:"day"`
	Month int32 `json:"month"`
	Year  int32 `json:"year"`
}

type GetCalendarDayRow struct {
	ID             string         `json:"id"`
	Day            int32          `json:"day"`
	Month          int32          `json:"month"`
	Year           int32          `json:"year"`
	Description    sql.NullString `json:"description"`
	IsPaidVacation bool           `json:"isPaidVacation"`
	TypeID         string         `json:"typeId"`
	TypeName       string         `json:"typeName"`
	TypeSystemName string         `json:"typeSystemName"`
}

func (q *Queries) GetCalendarDay(ctx context.Context, arg GetCalendarDayParams) (GetCalendarDayRow, error) {
	row := q.db.QueryRowContext(ctx, getCalendarDay, arg.Day, arg.Month, arg.Year)
	var i GetCalendarDayRow
	err := row.Scan(
		&i.ID,
		&i.Day,
		&i.Month,
		&i.Year,
		&i.Description,
		&i.IsPaidVacation,
		&i.TypeID,
		&i.TypeName,
		&i.TypeSystemName,
	)
	return i, err
}

const getCalendarDays = `-- name: GetCalendarDays :many

SELECT
    rc.id,
    rc.day,
    rc.month,
    rc.year,
    COALESCE(rc.description, '') as description,  -- Возвращаем пустую строку вместо NULL
    rc.is_paid_vacation,
    rc.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_calendar rc
INNER JOIN report_type rt ON rc.type_id = rt.id
WHERE rc.month = ? AND rc.year = ?
ORDER BY rc.day ASC
`

type GetCalendarDaysParams struct {
	Month int32 `json:"month"`
	Year  int32 `json:"year"`
}

type GetCalendarDaysRow struct {
	ID             string `json:"id"`
	Day            int32  `json:"day"`
	Month          int32  `json:"month"`
	Year           int32  `json:"year"`
	Description    string `json:"description"`
	IsPaidVacation bool   `json:"isPaidVacation"`
	TypeID         string `json:"typeId"`
	TypeName       string `json:"typeName"`
	TypeSystemName string `json:"typeSystemName"`
}

// ============================================
// REPORT_CALENDAR queries
// ============================================
func (q *Queries) GetCalendarDays(ctx context.Context, arg GetCalendarDaysParams) ([]GetCalendarDaysRow, error) {
	rows, err := q.db.QueryContext(ctx, getCalendarDays, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCalendarDaysRow
	for rows.Next() {
		var i GetCalendarDaysRow
		if err := rows.Scan(
			&i.ID,
			&i.Day,
			&i.Month,
			&i.Year,
			&i.Description,
			&i.IsPaidVacation,
			&i.TypeID,
			&i.TypeName,
			&i.TypeSystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCalendarDaysAll = `-- name: GetCalendarDaysAll :many
SELECT
    rc.id,
    rc.day,
    rc.month,
    rc.year,
    COALESCE(rc.description, '') as description,  -- Возвращаем пустую строку вместо NULL
    rc.is_paid_vacation,
    rc.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_calendar rc
INNER JOIN report_type rt ON rc.type_id = rt.id
WHERE rc.year = ?
ORDER BY rc.month ASC, rc.day ASC
`

type GetCalendarDaysAllRow struct {
	ID             string `json:"id"`
	Day            int32  `json:"day"`
	Month          int32  `json:"month"`
	Year           int32  `json:"year"`
	Description    string `json:"description"`
	IsPaidVacation bool   `json:"isPaidVacation"`
	TypeID         string `json:"typeId"`
	TypeName       string `json:"typeName"`
	TypeSystemName string `json:"typeSystemName"`
}

func (q *Queries) GetCalendarDaysAll(ctx context.Context, year int32) ([]GetCalendarDaysAllRow, error) {
	rows, err := q.db.QueryContext(ctx, getCalendarDaysAll, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCalendarDaysAllRow
	for rows.Next() {
		var i GetCalendarDaysAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Day,
			&i.Month,
			&i.Year,
			&i.Description,
			&i.IsPaidVacation,
			&i.TypeID,
			&i.TypeName,
			&i.TypeSystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCalendarDaysAllByType = `-- name: GetCalendarDaysAllByType :many
SELECT
    rc.id,
    rc.day,
    rc.month,
    rc.year,
    COALESCE(rc.description, '') as description,  -- Возвращаем пустую строку вместо NULL
    rc.is_paid_vacation,
    rc.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_calendar rc
INNER JOIN report_type rt ON rc.type_id = rt.id
WHERE rc.year = ? AND rt.system_name = ?
ORDER BY rc.month ASC, rc.day ASC
`

type GetCalendarDaysAllByTypeParams struct {
	Year       int32  `json:"year"`
	SystemName string `json:"systemName"`
}

type GetCalendarDaysAllByTypeRow struct {
	ID             string `json:"id"`
	Day            int32  `json:"day"`
	Month          int32  `json:"month"`
	Year           int32  `json:"year"`
	Description    string `json:"description"`
	IsPaidVacation bool   `json:"isPaidVacation"`
	TypeID         string `json:"typeId"`
	TypeName       string `json:"typeName"`
	TypeSystemName string `json:"typeSystemName"`
}

func (q *Queries) GetCalendarDaysAllByType(ctx context.Context, arg GetCalendarDaysAllByTypeParams) ([]GetCalendarDaysAllByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getCalendarDaysAllByType, arg.Year, arg.SystemName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCalendarDaysAllByTypeRow
	for rows.Next() {
		var i GetCalendarDaysAllByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Day,
			&i.Month,
			&i.Year,
			&i.Description,
			&i.IsPaidVacation,
			&i.TypeID,
			&i.TypeName,
			&i.TypeSystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCalendarDaysByType = `-- name: GetCalendarDaysByType :many
SELECT
    rc.id,
    rc.day,
    rc.month,
    rc.year,
    COALESCE(rc.description, '') as description,  -- Возвращаем пустую строку вместо NULL
    rc.is_paid_vacation,
    rc.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_calendar rc
INNER JOIN report_type rt ON rc.type_id = rt.id
WHERE rc.month = ? AND rc.year = ? AND rt.system_name = ?
ORDER BY rc.day ASC
`

type GetCalendarDaysByTypeParams struct {
	Month      int32  `json:"month"`
	Year       int32  `json:"year"`
	SystemName string `json:"systemName"`
}

type GetCalendarDaysByTypeRow struct {
	ID             string `json:"id"`
	Day            int32  `json:"day"`
	Month          int32  `json:"month"`
	Year           int32  `json:"year"`
	Description    string `json:"description"`
	IsPaidVacation bool   `json:"isPaidVacation"`
	TypeID         string `json:"typeId"`
	TypeName       string `json:"typeName"`
	TypeSystemName string `json:"typeSystemName"`
}

func (q *Queries) GetCalendarDaysByType(ctx context.Context, arg GetCalendarDaysByTypeParams) ([]GetCalendarDaysByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getCalendarDaysByType, arg.Month, arg.Year, arg.SystemName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCalendarDaysByTypeRow
	for rows.Next() {
		var i GetCalendarDaysByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Day,
			&i.Month,
			&i.Year,
			&i.Description,
			&i.IsPaidVacation,
			&i.TypeID,
			&i.TypeName,
			&i.TypeSystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendarDay = `-- name: UpdateCalendarDay :exec
UPDATE report_calendar
SET description = ?, type_id = ?
WHERE id = ?
`

type UpdateCalendarDayParams struct {
	Description sql.NullString `json:"description"`
	TypeID      string         `json:"typeId"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateCalendarDay(ctx context.Context, arg UpdateCalendarDayParams) error {
	_, err := q.db.ExecContext(ctx, updateCalendarDay, arg.Description, arg.TypeID, arg.ID)
	return err
}
