// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_setting.sql

package repo

import (
	"context"
)

const getVacationDuration = `-- name: GetVacationDuration :one

SELECT vacation_duration
FROM report_setting
WHERE id = 1
`

// ============================================
// REPORT_SETTING queries
// ============================================
func (q *Queries) GetVacationDuration(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getVacationDuration)
	var vacation_duration int32
	err := row.Scan(&vacation_duration)
	return vacation_duration, err
}
