// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_user.sql

package repo

import (
	"context"
)

const checkReportUserExists = `-- name: CheckReportUserExists :one
SELECT COUNT(*) as exists_count
FROM report_user
WHERE user_id = ? AND day = ? AND month = ? AND year = ?
`

type CheckReportUserExistsParams struct {
	UserID string `json:"userId"`
	Day    int32  `json:"day"`
	Month  int32  `json:"month"`
	Year   int32  `json:"year"`
}

func (q *Queries) CheckReportUserExists(ctx context.Context, arg CheckReportUserExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkReportUserExists,
		arg.UserID,
		arg.Day,
		arg.Month,
		arg.Year,
	)
	var exists_count int64
	err := row.Scan(&exists_count)
	return exists_count, err
}

const createReportUser = `-- name: CreateReportUser :exec
INSERT INTO report_user (id, user_id, day, month, year, hours, type_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateReportUserParams struct {
	ID     string  `json:"id"`
	UserID string  `json:"userId"`
	Day    int32   `json:"day"`
	Month  int32   `json:"month"`
	Year   int32   `json:"year"`
	Hours  float64 `json:"hours"`
	TypeID string  `json:"typeId"`
}

func (q *Queries) CreateReportUser(ctx context.Context, arg CreateReportUserParams) error {
	_, err := q.db.ExecContext(ctx, createReportUser,
		arg.ID,
		arg.UserID,
		arg.Day,
		arg.Month,
		arg.Year,
		arg.Hours,
		arg.TypeID,
	)
	return err
}

const deleteReportUser = `-- name: DeleteReportUser :exec
DELETE FROM report_user
WHERE user_id = ? AND day = ? AND month = ? AND year = ?
`

type DeleteReportUserParams struct {
	UserID string `json:"userId"`
	Day    int32  `json:"day"`
	Month  int32  `json:"month"`
	Year   int32  `json:"year"`
}

func (q *Queries) DeleteReportUser(ctx context.Context, arg DeleteReportUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteReportUser,
		arg.UserID,
		arg.Day,
		arg.Month,
		arg.Year,
	)
	return err
}

const getReportUserById = `-- name: GetReportUserById :one
SELECT
    ru.id,
    ru.user_id,
    ru.day,
    ru.month,
    ru.year,
    ru.hours,
    ru.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_user ru
INNER JOIN report_type rt ON ru.type_id = rt.id
WHERE ru.id = ?
`

type GetReportUserByIdRow struct {
	ID             string  `json:"id"`
	UserID         string  `json:"userId"`
	Day            int32   `json:"day"`
	Month          int32   `json:"month"`
	Year           int32   `json:"year"`
	Hours          float64 `json:"hours"`
	TypeID         string  `json:"typeId"`
	TypeName       string  `json:"typeName"`
	TypeSystemName string  `json:"typeSystemName"`
}

func (q *Queries) GetReportUserById(ctx context.Context, id string) (GetReportUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getReportUserById, id)
	var i GetReportUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.Month,
		&i.Year,
		&i.Hours,
		&i.TypeID,
		&i.TypeName,
		&i.TypeSystemName,
	)
	return i, err
}

const getReportUserCountByType = `-- name: GetReportUserCountByType :one
SELECT COUNT(DISTINCT day) as days_count
FROM report_user
WHERE user_id = ? AND month = ? AND year = ? AND type_id = ?
`

type GetReportUserCountByTypeParams struct {
	UserID string `json:"userId"`
	Month  int32  `json:"month"`
	Year   int32  `json:"year"`
	TypeID string `json:"typeId"`
}

func (q *Queries) GetReportUserCountByType(ctx context.Context, arg GetReportUserCountByTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReportUserCountByType,
		arg.UserID,
		arg.Month,
		arg.Year,
		arg.TypeID,
	)
	var days_count int64
	err := row.Scan(&days_count)
	return days_count, err
}

const getReportUserCountWork = `-- name: GetReportUserCountWork :one
SELECT COUNT(DISTINCT day) as days_count
FROM report_user ru
INNER JOIN report_type rt ON ru.type_id = rt.id
WHERE ru.user_id = ? AND ru.month = ? AND ru.year = ? AND (rt.system_name = 'work' OR rt.system_name = 'weekend')
`

type GetReportUserCountWorkParams struct {
	UserID string `json:"userId"`
	Month  int32  `json:"month"`
	Year   int32  `json:"year"`
}

func (q *Queries) GetReportUserCountWork(ctx context.Context, arg GetReportUserCountWorkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReportUserCountWork, arg.UserID, arg.Month, arg.Year)
	var days_count int64
	err := row.Scan(&days_count)
	return days_count, err
}

const getReportUserForMonth = `-- name: GetReportUserForMonth :many

SELECT
    ru.id,
    ru.user_id,
    ru.day,
    ru.month,
    ru.year,
    ru.hours,
    ru.type_id,
    rt.name as type_name,
    rt.system_name as type_system_name
FROM report_user ru
INNER JOIN report_type rt ON ru.type_id = rt.id
WHERE ru.user_id = ? AND ru.month = ? AND ru.year = ?
ORDER BY ru.day ASC
`

type GetReportUserForMonthParams struct {
	UserID string `json:"userId"`
	Month  int32  `json:"month"`
	Year   int32  `json:"year"`
}

type GetReportUserForMonthRow struct {
	ID             string  `json:"id"`
	UserID         string  `json:"userId"`
	Day            int32   `json:"day"`
	Month          int32   `json:"month"`
	Year           int32   `json:"year"`
	Hours          float64 `json:"hours"`
	TypeID         string  `json:"typeId"`
	TypeName       string  `json:"typeName"`
	TypeSystemName string  `json:"typeSystemName"`
}

// ============================================
// REPORT_USER queries
// ============================================
func (q *Queries) GetReportUserForMonth(ctx context.Context, arg GetReportUserForMonthParams) ([]GetReportUserForMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getReportUserForMonth, arg.UserID, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportUserForMonthRow
	for rows.Next() {
		var i GetReportUserForMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Day,
			&i.Month,
			&i.Year,
			&i.Hours,
			&i.TypeID,
			&i.TypeName,
			&i.TypeSystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportUserTotalHours = `-- name: GetReportUserTotalHours :one
SELECT CAST(COALESCE(SUM(hours), 0.0) AS FLOAT) AS total_hours
FROM report_user
WHERE user_id = ? AND month = ? AND year = ?
`

type GetReportUserTotalHoursParams struct {
	UserID string `json:"userId"`
	Month  int32  `json:"month"`
	Year   int32  `json:"year"`
}

func (q *Queries) GetReportUserTotalHours(ctx context.Context, arg GetReportUserTotalHoursParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getReportUserTotalHours, arg.UserID, arg.Month, arg.Year)
	var total_hours float64
	err := row.Scan(&total_hours)
	return total_hours, err
}

const updateReportUser = `-- name: UpdateReportUser :exec
UPDATE report_user
SET hours = ?, type_id = ?
WHERE id = ?
`

type UpdateReportUserParams struct {
	Hours  float64 `json:"hours"`
	TypeID string  `json:"typeId"`
	ID     string  `json:"id"`
}

func (q *Queries) UpdateReportUser(ctx context.Context, arg UpdateReportUserParams) error {
	_, err := q.db.ExecContext(ctx, updateReportUser, arg.Hours, arg.TypeID, arg.ID)
	return err
}
